[package]
name = "moonshine-spawn"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A lightweight spawn utility for Bevy"
homepage = "https://github.com/Zeenobit/moonshine_spawn"
repository = "https://github.com/Zeenobit/moonshine_spawn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.13.*"
bevy_ecs = "0.13.*"
bevy_reflect = "0.13.*"
bevy_utils = "0.13.*"
bevy_hierarchy = "0.13.*"

[dev-dependencies]
bevy = "0.13.*"
